name: Go Package Release
on:
  push:
    tags:
      - 'lambda/v*.*.*'
permissions:
  packages: write


jobs:
  go-auto-ci:
    uses:  tommzn/github-ci/.github/workflows/go.lambda.image.build.yml@v1.0.64