name: Protobuf Compile
on:
  push:
    branches:
      - main
      
jobs:
  proto-compile:
    name: Compile Proto messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.goversion }}
      - name: Install Protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          protoc --version 
      - name: Compile
        run: protoc --go_out=./ *.proto
      - name: Upload Golang artifacts
        uses: actions/upload-artifact@v2
        with:
          name: proto-sources
          path: ./*.pb.go
          retention-days: 1

  publish-proto:
    name: Publish Compiled proto messages in a proto-compile branch.
    runs-on: ubuntu-latest
    needs: proto-compile
    continue-on-error: true
    env:
        PROTO_BRANCH: proto-compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Protobuf compiler
        run: git checkout ${{ env.PROTO_BRANCH }}
      - name: Download Golang events
        uses: actions/download-artifact@v2
        with:
          name: proto-sources
      - name: Commir & Push
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git add -A
          git commit -am "Update proto sources.$GITHUB_SHA"
          git push oritin ${{ env.PROTO_BRANCH }}
